### ISSUE TITLE
How to get validate-on="blur" working ?

### ISSUE THREAD

**Issue by FilipePedro** [SteefTheBeef/slick-angular-validation#2]
Hi... I am trying to use slick-angular-validation with the option validate-on="blur" active but i don't see it working like expected...I didn't find any reference to any piece of code that can implement this so can oyu tell me if the latest version of the js file is adapted to do this ?

Best Regards,

**Comment by SteefTheBeef** [comment]
Hello, you are correct, it is not implemented. But you can use ng-model-options="{ updateOn: 'mousedown blur' }" on the input field to get that behavior!

**Comment by SteefTheBeef** [comment]
Hi, i have released another version which supports validate-on.

## Validate On

#### Per field

Default is to validate when the model changes. However, validate on blur is also supported. 

``` html
<input type="text" name="blurme" ng-model="data.blurme" validate="minlength:3" validate-on="blur">`
```

`ng-model-options="{ updateOn: 'blur' }"` does the exact same thing, but requires more text!

#### Globally

``` JavaScript
app.config(["SlickAngularValidationProvider", function (SlickAngularValidationProvider) {
  SlickAngularValidationProvider.setValidateOn('blur);
}])
```
