### ISSUE TITLE
validateMessages

### ISSUE THREAD

**Issue by oluaPt** [SteefTheBeef/slick-angular-validation#3]
Hi

In file dist/slick-angular-validation.js at line 121:
attrs.messages.split('|').forEach(function(message) {

I needed to fix to: 
attrs.validateMessages.split('|').forEach(function(message) {

can you confirm its right?

Ty and gj!

**Comment by SteefTheBeef** [comment]
Hi

You are absolutely right.

I have corrected the bug with a new release.
